name: ViewIt
version: "${version}"
main: net.t7seven7t.viewit.ViewItPlugin
author: t7seven7t
description: >
             An API designed to make it easier for developers to display content to their audience.
commands:
  scoreboard:
    aliases: [viewit]
    usage: /<command>
    description: Change your scoreboard settings
    permission: viewit.scoreboard
permissions:
  viewit.scoreboard.toggle:
    description: Allows users to toggle their scoreboard on/off
    default: true
  viewit.scoreboard.reload:
    description: Allows users to reload the scoreboard elements from config using /scoreboard reload
    default: op
